[pytest]
markers =
    api: API-level tests
    integration: End-to-end integration tests
    ui: Selenium UI tests
    smoke: Smoke / sanity check
    sanity: Sanity tests
    regression: Regression tests

addopts = --alluredir=allure-results -v
